### PR TITLE
fix for kinetic

### PR DESCRIPTION
**Pull request by furushchev**

### CODE REVIEW

**Comment by dirk-thomas** [comment]
@ablasdel @TheDash Ping to the maintainers...

**Comment by UltronDestroyer** [comment]
I haven't maintained this for a year or so. Not sure who is going to take it over.

**Comment by dirk-thomas** [comment]
You are currently still listed as the maintainer of this package (https://github.com/PR2/rqt_pr2_dashboard/blob/f2fd1d364ee80d812c947d4ba9de3c96c897cbb1/package.xml#L9). So e.g. any notification email from the buildfarm is being sent to you.

**Comment by DLu** [comment]
I have reviewed this PR and approve, but commenting is all I'm authorized for. It'd be best if it was tested in other distros besides kinetic, but I'm guessing it'd work. 

Note: Releasing this package for kinetic would rely on https://github.com/PR2/pr2_power_drivers/issues/67

**Comment by furushchev** [comment]
@DLu Thank you for review! I also checked that this works on indigo.

**Comment by UltronDestroyer** [comment]
@dirk-thomas Out of my hands now. AFAIK there is no official PR2 maintainership since Scott Hassan ceased the funding for the PR2 support. The community unfortunately will have to find someone else to take maintainership/release responsibility over them as I'm unable to at the moment.

**Comment by k-okada** [comment]
@TheClearpathDash we have proposed the initiative to support this kind of packages at roscon 2017. See
video: https://vimeo.com/236129109#t=34m30s
slides: https://roscon.ros.org/2017/presentations/ROSCon%202017%20Lightning%20113.pdf

and I have start writing a draft of this procedure at
https://github.com/ros-infrastructure/rep/pull/150 (https://github.com/k-okada/rep/blob/0d5b63cc04ba945fec73650f9453d576b939a67a/rep-0152.rst ).

If you're ok, please look at these ticket and add @k-okada to admin/write manber of these repositories.
https://github.com/PR2/pr2_power_drivers/pull/68
https://github.com/PR2/rqt_pr2_dashboard/pull/20

**Comment by k-okada** [comment]
also please add me to pr2_power_drivers-release and rqt_pr2_dashboard-release repositories.

**Comment by v4hn** [comment]
+1 for the pull-request here.

**Comment by awesomebytes** [comment]
+1 for the PR, looks good to me.

**Comment by k-okada** [comment]
Merged, It seems I have write permission, but I do not have admin permission...

**Pull request merged**
